
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('uniform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=2)),
                ('batting_hand', models.CharField(max_length=1)),
                ('throwing_hand', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'batter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('uniform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=2)),
                ('throwing_hand', models.CharField(max_length=1)),
                ('batting_hand', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pitcher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_batter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_number', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='他ユーザーに公開しますか')),
                ('batting_hand', models.CharField(blank=True, max_length=1, null=True)),
                ('throwing_hand', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'user_batter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_number', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='他ユーザーに公開しますか')),
                ('throwing_hand', models.CharField(blank=True, max_length=1, null=True)),
                ('batting_hand', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'user_pitcher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BattingStatus',
            fields=[
                ('uniform_number', models.OneToOneField(db_column='uniform_number', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='battingstatus_player', serialize=False, to='player_app.batter')),
                ('games', models.IntegerField(blank=True, null=True)),
                ('numPlate', models.IntegerField(blank=True, null=True)),
                ('numBat', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('hit2nd', models.IntegerField(blank=True, null=True)),
                ('hit3rd', models.IntegerField(blank=True, null=True)),
                ('homeruns', models.IntegerField(blank=True, null=True)),
                ('baseHits', models.IntegerField(blank=True, null=True)),
                ('getpoint', models.IntegerField(blank=True, null=True)),
                ('steal', models.IntegerField(blank=True, null=True)),
                ('missedSteal', models.IntegerField(blank=True, null=True)),
                ('bants', models.IntegerField(blank=True, null=True)),
                ('sacFry', models.IntegerField(blank=True, null=True)),
                ('fourballs', models.IntegerField(blank=True, null=True)),
                ('intWalk', models.IntegerField(blank=True, null=True)),
                ('deadballs', models.IntegerField(blank=True, null=True)),
                ('strikeOut', models.IntegerField(blank=True, null=True)),
                ('doublePlay', models.IntegerField(blank=True, null=True)),
                ('errors', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batting_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitching_status',
            fields=[
                ('uniform_number', models.OneToOneField(db_column='uniform_number', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pitchingstatus_player', serialize=False, to='player_app.pitcher')),
                ('games', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('lose', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('hold', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('fullIning', models.IntegerField(blank=True, null=True)),
                ('perfect', models.IntegerField(blank=True, null=True)),
                ('noFour', models.IntegerField(blank=True, null=True)),
                ('batter', models.IntegerField(blank=True, null=True)),
                ('ining', models.IntegerField(blank=True, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('homerun', models.IntegerField(blank=True, null=True)),
                ('fourball', models.IntegerField(blank=True, null=True)),
                ('int_Walk', models.IntegerField(blank=True, null=True)),
                ('deadBall', models.IntegerField(blank=True, null=True)),
                ('strikeOut', models.IntegerField(blank=True, null=True)),
                ('wildPitch', models.IntegerField(blank=True, null=True)),
                ('balk', models.IntegerField(blank=True, null=True)),
                ('lostScore', models.IntegerField(blank=True, null=True)),
                ('earnedRun', models.IntegerField(blank=True, null=True)),
                ('ERA', models.FloatField(blank=True, null=True)),
                ('QS', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitching_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_batting_status',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='batting_status', serialize=False, to='player_app.user_batter')),
                ('games', models.IntegerField(blank=True, null=True)),
                ('numPlate', models.IntegerField(blank=True, null=True)),
                ('numBat', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('hit2nd', models.IntegerField(blank=True, null=True)),
                ('hit3rd', models.IntegerField(blank=True, null=True)),
                ('homeruns', models.IntegerField(blank=True, null=True)),
                ('baseHits', models.IntegerField(blank=True, null=True)),
                ('getpoint', models.IntegerField(blank=True, null=True)),
                ('steal', models.IntegerField(blank=True, null=True)),
                ('missedSteal', models.IntegerField(blank=True, null=True)),
                ('bants', models.IntegerField(blank=True, null=True)),
                ('sacFry', models.IntegerField(blank=True, null=True)),
                ('fourballs', models.IntegerField(blank=True, null=True)),
                ('intWalk', models.IntegerField(blank=True, null=True)),
                ('deadballs', models.IntegerField(blank=True, null=True)),
                ('strikeOut', models.IntegerField(blank=True, null=True)),
                ('doublePlay', models.IntegerField(blank=True, null=True)),
                ('errors', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_batting_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_pitching_status',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pitching_status', serialize=False, to='player_app.user_pitcher')),
                ('games', models.IntegerField(blank=True, null=True)),
                ('win', models.IntegerField(blank=True, null=True)),
                ('lose', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('hold', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('fullIning', models.IntegerField(blank=True, null=True)),
                ('perfect', models.IntegerField(blank=True, null=True)),
                ('noFour', models.IntegerField(blank=True, null=True)),
                ('batter', models.IntegerField(blank=True, null=True)),
                ('ining', models.IntegerField(blank=True, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('homerun', models.IntegerField(blank=True, null=True)),
                ('fourball', models.IntegerField(blank=True, null=True)),
                ('int_Walk', models.IntegerField(blank=True, null=True)),
                ('deadBall', models.IntegerField(blank=True, null=True)),
                ('strikeOut', models.IntegerField(blank=True, null=True)),
                ('wildPitch', models.IntegerField(blank=True, null=True)),
                ('balk', models.IntegerField(blank=True, null=True)),
                ('lostScore', models.IntegerField(blank=True, null=True)),
                ('earnedRun', models.IntegerField(blank=True, null=True)),
                ('ERA', models.FloatField(blank=True, null=True)),
                ('QS', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_pitching_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('player_count', models.IntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
